mappings:
  BetterButtonAction: UncleCheese\BetterButtons\Actions\BetterButtonAction
  BetterButtonCancelAction: UncleCheese\BetterButtons\Actions\BetterButtonCancelAction
  BetterButtonCustomAction: UncleCheese\BetterButtons\Actions\BetterButtonCustomAction
  BetterButtonFrontendLinksAction: UncleCheese\BetterButtons\Actions\BetterButtonFrontendLinksAction
  BetterButtonLink: UncleCheese\BetterButtons\Actions\BetterButtonLink
  BetterButtonNestedForm: UncleCheese\BetterButtons\Actions\BetterButtonNestedForm
  BetterButtonPrevNextAction: UncleCheese\BetterButtons\Actions\BetterButtonPrevNextAction
  BetterButton: UncleCheese\BetterButtons\Buttons\BetterButton
  BetterButton_Delete: UncleCheese\BetterButtons\Buttons\BetterButton_Delete
  BetterButton_New: UncleCheese\BetterButtons\Buttons\BetterButton_New
  BetterButton_Publish: UncleCheese\BetterButtons\Buttons\BetterButton_Publish
  BetterButton_PublishAndAdd: UncleCheese\BetterButtons\Buttons\BetterButton_PublishAndAdd
  BetterButton_PublishAndClose: UncleCheese\BetterButtons\Buttons\BetterButton_PublishAndClose
  BetterButton_Rollback: UncleCheese\BetterButtons\Buttons\BetterButton_Rollback
  BetterButton_Save: UncleCheese\BetterButtons\Buttons\BetterButton_Save
  BetterButton_SaveAndAdd: UncleCheese\BetterButtons\Buttons\BetterButton_SaveAndAdd
  BetterButton_SaveAndClose: UncleCheese\BetterButtons\Buttons\BetterButton_SaveAndClose
  BetterButton_SaveAndNext: UncleCheese\BetterButtons\Buttons\BetterButton_SaveAndNext
  BetterButton_SaveAndPrev: UncleCheese\BetterButtons\Buttons\BetterButton_SaveAndPrev
  BetterButton_SaveDraft: UncleCheese\BetterButtons\Buttons\BetterButton_SaveDraft
  BetterButton_Unpublish: UncleCheese\BetterButtons\Buttons\BetterButton_Unpublish
  BetterButtonsCustomActionRequest: UncleCheese\BetterButtons\Controllers\BetterButtonsCustomActionRequest
  BetterButtonsNestedFormRequest: UncleCheese\BetterButtons\Controllers\BetterButtonsNestedFormRequest
  BetterButtonDataObject: UncleCheese\BetterButtons\Extensions\BetterButtonDataObject
  BetterButtonGroupable: UncleCheese\BetterButtons\Extensions\BetterButtonGroupable
  GridFieldBetterButtonsItemRequest: UncleCheese\BetterButtons\Extensions\GridFieldBetterButtonsItemRequest
  DropdownFormAction: UncleCheese\BetterButtons\FormFields\DropdownFormAction
  BetterButton_Versioned: UncleCheese\BetterButtons\Interfaces\BetterButton_Versioned
  BetterButtonInterface: UncleCheese\BetterButtons\Interfaces\BetterButtonInterface
