<?php

use SilverStripe\CMS\Model\SiteTree;
use SilverStripe\Forms\TreeDropdownField;
use SilverStripe\Forms\Form;
use Silverstripe\Forms\Formfield;
use SilverStripe\Forms\TextField;
use SilverStripe\Forms\GridField\GridField;
use SilverStripe\Forms\GridField\GridFieldConfig_RecordEditor;
use UndefinedOffset\SortableGridField\Forms\GridFieldSortableRows;
use SilverStripe\ORM\DataList;
use SilverStripe\AssetAdmin\Forms\UploadField;
use SilverStripe\ORM\SS_List;
use Silverstripe\Assets\File;

class Contract extends Page {

    private static $db = [
        'Description' => 'Text'
    ];

    private static $has_one = [
        'Assets' => File::class
    ];

    private static $allowed_children = [];

    private static $can_be_root = false;

    public function getCMSFields()
    {
        $fields = parent::getCMSFields();
        $fields->addFieldsToTab("Root.Assets", [
            UploadField::create("Assets", "Asset")->setFolderName("Contracts"),
        ]);
        return $fields; // TODO: Change the autogenerated stub
    }


}

class ContractController extends PageController {

}