<?php

use SilverStripe\CMS\Model\SiteTree;
use SilverStripe\Forms\TreeDropdownField;
use SilverStripe\Forms\Form;
use Silverstripe\Forms\Formfield;
use SilverStripe\Forms\TextField;

class Page extends SiteTree
{
    private static $db = [
        'HeaderTitle' => 'Text'
    ];

    private static $has_one = [
//        'LinkedPage' => SiteTree::class
    ];

    public function getCMSFields()
    {
        $fields = parent::getCMSFields();
//        Let's not get into bad habits now. Page Name is decoupled from Meta Title and Menu Title, so this is a bit unnecessary.
//        The only spot of bother will be URL segment, but w/e
//        $fields->insertAfter("MenuTitle",
//           TextField::create('HeaderTitle', 'Header Title')->setDescription("Alternate on-page title. If set, this will be the title that is displayed on the page itself.")
//        );
        //$fields->dataFieldByName("ElementalArea")->setTitle("Content blocks")->setDescription("Select which type of content block you want to add here. Above, you can edit, reorder or delete existing blocks.");
        /*$fields->addFieldsToTab("Root.Main",[
           new TreeDropdownField('LinkedPageID', 'Linked Page', SiteTree::class)
        ]);*/
        return $fields; // TODO: Change the autogenerated stub
    }
}
