---
Name: workflowconfig
After:
  - 'framework/*'
  - 'cms/*'
---
SiteTree:
  extensions:
    - WorkflowApplicable
CMSPageEditController:
  extensions:
    - AdvancedWorkflowExtension
GridFieldDetailForm_ItemRequest:
  extensions:
    - AdvancedWorkflowExtension
LeftAndMain:
  extra_requirements_css:
    - advancedworkflow/css/AdvancedWorkflowAdmin.css

---
Name: workflow_jobs
Only:
  moduleexists: queuedjobs
---
Injector:
  WorkflowReminderJob:
    properties:
      queuedJobService: %$QueuedJobService
